---
install:
  - set QTDIR=C:\Qt\5.12\mingw73_64
  - set MINGWDIR=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin
before_build:
  - qmake dsktowoz2.pro
build_script:
  - mingw32-make
  - 7z a ${APPVEYOR_PROJECT_NAME}-win.zip release\${APPVEYOR_PROJECT_NAME}.exe
artifacts:
  - path: '*.zip'
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: uTlXzA/1qIu1k02Hb3DOrP60/eBtPN1QbqpEWAgoCBSfr8FCJuheQsOW226kH0yzGbPyI6wB2cMEzrehWnWx3Au0od1CXVH0fs4Ob4KbJd0cTT2ML+OVTp8eKj3wBz6YTQ8E0f66eawOeZwWTuFsnkkPPNyI/pz38XAJIvS4sHQoVphdUt/gG0zMnwKA14SPvdkpsfaD/OcIFuvD7HRrfZG6tzZE/htgWsum5XTyYP9oZPalT5pW+vdl6VIdZbhOnc/ityTvm2PW89yBlnyP3U14eU79KnvFJbYhGpRQChHb06/m//CmpOQeJnEWIczf6Y6NvUWhk3zVuNflPaCVpouK40H06kE8iyCJBcpiOd+Rza+19e3n6FQYj9h+caOzgzWokDnm/6wEqTBpcY0u5U2fhC9Ky3Eeg8JGHoLJPZ5RSct83q4oV1J+u8geJF2Lun95SQKae5AZpHeaowLBV8ABAAZsnCjPJHA8hSdXEwtgSAVyXIRG84JN6iXIfiQZ5Sb0cPmuKaYx3yC5f8mUsrlZ3bnRHsxsf4IuWW8q2EyVmmzawGMzDDK6eRwP3emdl4Yz1S76T6D1vPJxQiV1CU6OdIzrkiGENNFUzpMtIbLhQVTYFP3j3cEf/1zDXT0dyae8l0Y9vfWqZRl530AqLfVGGtu0DiuUzpUf7DMlPrk=
  artifact: '*.zip'
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
