matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: cpp
      compiler:
        - gcc
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
    - os: osx
      before_install:
        - brew update
      install:
        - brew install qt5

script:
  - qmake
  - make
