language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
    - os: osx
      env:
        - PATH=/usr/local/opt/qt/bin:$PATH
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt
    - os: windows
      before_install:
        - curl -LO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
        - curl -LO https://raw.githubusercontent.com/wireshark/wireshark/master/tools/qt-installer-windows.qs
      env:
        - PATH=/c/Users/travis/Qt/Tools/mingw730_64/bin:/c/Users/travis/Qt/5.12.0/mingw73_64/bin:$PATH
      install:
        - ./qt-unified-windows-x86-online.exe --script qt-installer-windows.qs
        - choco install make

script:
  - qmake
  - make
