language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
    - os: osx
      install:
        - brew install qt
        - ls -l /usr/local/bin
        - ls -l /usr/local/opt/qt

script:
  - qmake
  - make
