language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
    - os: osx
      env:
        - PATH=/usr/local/opt/qt/bin:$PATH
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt
    - os: windows
      install:
        - choco install qt-sdk-windows-x64-mingw_seh


script:
  - qmake
  - make
