language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
    - os: osx
      env:
        - PATH=/usr/local/opt/qt/bin:$PATH
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt

script:
  - qmake
  - make
